/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauricio Franco Franciscio
 */
public
        class ConsultaPorRNE extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaPorRNE
     */
    public
            ConsultaPorRNE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EtiquetaConsultaPorRNE = new javax.swing.JLabel();
        SeparadorDatosEmpresa = new javax.swing.JSeparator();
        EtiquetaDatosEmpresa = new javax.swing.JLabel();
        labelEmp_CUIL = new javax.swing.JLabel();
        labelEmp_NombreEmpresa = new javax.swing.JLabel();
        labelEmp_RazonSocial = new javax.swing.JLabel();
        labelEmp_Telefono = new javax.swing.JLabel();
        labelEmp_Email = new javax.swing.JLabel();
        labelNumRNE = new javax.swing.JLabel();
        textFieldRNE = new javax.swing.JTextField();
        BuscarRNE = new javax.swing.JButton();
        SeparadorPAAsociado = new javax.swing.JSeparator();
        EtiquetaPAAsociado = new javax.swing.JLabel();
        ScrollpanelPAAsociado = new javax.swing.JScrollPane();
        TablaPAAsociado = new javax.swing.JTable();
        SeparadorDatosEstablecimiento = new javax.swing.JSeparator();
        labelTitulo = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        labelFechaCarga = new javax.swing.JLabel();
        textFieldFechaCarga = new javax.swing.JTextField();
        labelNroFactura = new javax.swing.JLabel();
        textFieldNroFactura = new javax.swing.JTextField();
        lavelCategoria = new javax.swing.JLabel();
        textFieldCategoria = new javax.swing.JTextField();
        labelLocalidad = new javax.swing.JLabel();
        textFieldLocalidad = new javax.swing.JTextField();
        textFieldFVencimientoRNE = new javax.swing.JTextField();
        labelFVencimientoRNE = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        textFieldTelefono = new javax.swing.JTextField();
        textFieldDireccion = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        textFieldCUIT = new javax.swing.JTextField();
        textFieldNombreEmpresa = new javax.swing.JTextField();
        textFieldRazonSocial = new javax.swing.JTextField();
        textFieldTelefonoEmpresa = new javax.swing.JTextField();
        textFieldEmailEmpresa = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        EtiquetaConsultaPorRNE.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        EtiquetaConsultaPorRNE.setForeground(new java.awt.Color(0, 51, 0));
        EtiquetaConsultaPorRNE.setText("Consulta por RNE ");

        EtiquetaDatosEmpresa.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        EtiquetaDatosEmpresa.setForeground(new java.awt.Color(0, 51, 0));
        EtiquetaDatosEmpresa.setText("Datos de la empresa ");

        labelEmp_CUIL.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelEmp_CUIL.setText("CUIT: ");

        labelEmp_NombreEmpresa.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelEmp_NombreEmpresa.setText("Nombre: ");

        labelEmp_RazonSocial.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelEmp_RazonSocial.setText("Razon Social: ");

        labelEmp_Telefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelEmp_Telefono.setText("Telefono: ");

        labelEmp_Email.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelEmp_Email.setText("Email: ");

        labelNumRNE.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelNumRNE.setText("Numero RNE: ");

        textFieldRNE.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textFieldRNE.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldRNE.setText("32132132");
        textFieldRNE.setToolTipText("");
        textFieldRNE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        textFieldRNE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldRNEKeyPressed(evt);
            }
        });

        BuscarRNE.setBackground(new java.awt.Color(255, 255, 255));
        BuscarRNE.setForeground(new java.awt.Color(255, 255, 255));
        BuscarRNE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Search_sombrapx.png"))); // NOI18N
        BuscarRNE.setBorder(null);
        BuscarRNE.setBorderPainted(false);
        BuscarRNE.setContentAreaFilled(false);
        BuscarRNE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BuscarRNEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuscarRNEMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarRNEMousePressed(evt);
            }
        });
        BuscarRNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarRNEActionPerformed(evt);
            }
        });

        EtiquetaPAAsociado.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        EtiquetaPAAsociado.setForeground(new java.awt.Color(0, 51, 0));
        EtiquetaPAAsociado.setText("Producto Alimenticio Asociado");

        TablaPAAsociado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TablaPAAsociado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numero RNPA", "Numero RNE", "Nombre Producto", "Vencimiento RNPA", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPAAsociado.setSelectionBackground(new java.awt.Color(76, 140, 74));
        ScrollpanelPAAsociado.setViewportView(TablaPAAsociado);

        labelTitulo.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 51, 0));
        labelTitulo.setText("Establecimiento");

        textFieldNombre.setEditable(false);
        textFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        textFieldNombre.setEnabled(false);

        labelNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelNombre.setText("Nombre: ");

        labelFechaCarga.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelFechaCarga.setText("Fecha Carga:");

        textFieldFechaCarga.setEditable(false);
        textFieldFechaCarga.setBackground(new java.awt.Color(255, 255, 255));
        textFieldFechaCarga.setEnabled(false);

        labelNroFactura.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelNroFactura.setText("Nro Factura:");

        textFieldNroFactura.setEditable(false);
        textFieldNroFactura.setBackground(new java.awt.Color(255, 255, 255));
        textFieldNroFactura.setEnabled(false);

        lavelCategoria.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lavelCategoria.setText("Categoria:");

        textFieldCategoria.setEditable(false);
        textFieldCategoria.setBackground(new java.awt.Color(255, 255, 255));
        textFieldCategoria.setEnabled(false);

        labelLocalidad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelLocalidad.setText("Localidad:");

        textFieldLocalidad.setEditable(false);
        textFieldLocalidad.setBackground(new java.awt.Color(255, 255, 255));
        textFieldLocalidad.setEnabled(false);

        textFieldFVencimientoRNE.setEditable(false);
        textFieldFVencimientoRNE.setBackground(new java.awt.Color(255, 255, 255));
        textFieldFVencimientoRNE.setEnabled(false);

        labelFVencimientoRNE.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelFVencimientoRNE.setText("Fecha vencimiento RNE:");

        labelTelefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelTelefono.setText("Telefono: ");

        textFieldTelefono.setEditable(false);
        textFieldTelefono.setBackground(new java.awt.Color(255, 255, 255));
        textFieldTelefono.setEnabled(false);

        textFieldDireccion.setEditable(false);
        textFieldDireccion.setBackground(new java.awt.Color(255, 255, 255));
        textFieldDireccion.setEnabled(false);

        labelDireccion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelDireccion.setText("Direccion:");

        textFieldCUIT.setEditable(false);
        textFieldCUIT.setBackground(new java.awt.Color(255, 255, 255));
        textFieldCUIT.setEnabled(false);

        textFieldNombreEmpresa.setEditable(false);
        textFieldNombreEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        textFieldNombreEmpresa.setEnabled(false);

        textFieldRazonSocial.setEditable(false);
        textFieldRazonSocial.setBackground(new java.awt.Color(255, 255, 255));
        textFieldRazonSocial.setEnabled(false);

        textFieldTelefonoEmpresa.setEditable(false);
        textFieldTelefonoEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        textFieldTelefonoEmpresa.setEnabled(false);

        textFieldEmailEmpresa.setEditable(false);
        textFieldEmailEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        textFieldEmailEmpresa.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SeparadorDatosEmpresa, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(SeparadorDatosEstablecimiento)
            .addComponent(SeparadorPAAsociado)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ScrollpanelPAAsociado, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(EtiquetaDatosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(labelNumRNE, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldRNE, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BuscarRNE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EtiquetaConsultaPorRNE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(EtiquetaPAAsociado))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFechaCarga)
                            .addComponent(labelNroFactura)
                            .addComponent(lavelCategoria)
                            .addComponent(labelNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldFechaCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDireccion)
                                        .addGap(3, 3, 3))
                                    .addComponent(labelTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFVencimientoRNE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelLocalidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldLocalidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldFVencimientoRNE, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEmp_NombreEmpresa)
                                    .addComponent(labelEmp_CUIL))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldNombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(textFieldCUIT)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelEmp_RazonSocial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldRazonSocial)))
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelEmp_Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(labelEmp_Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldTelefonoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(textFieldEmailEmpresa))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaConsultaPorRNE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNumRNE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldRNE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BuscarRNE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeparadorDatosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EtiquetaDatosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmp_CUIL)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelEmp_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldEmailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelEmp_NombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelEmp_Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldTelefonoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmp_RazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeparadorDatosEstablecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombre)
                            .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldFechaCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFechaCarga))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNroFactura))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(textFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lavelCategoria)
                                .addGap(2, 2, 2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDireccion)
                            .addComponent(textFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelefono)
                            .addComponent(textFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldFVencimientoRNE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFVencimientoRNE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldLocalidad)
                            .addComponent(labelLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeparadorPAAsociado, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EtiquetaPAAsociado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollpanelPAAsociado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldRNEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldRNEKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            buscarRNE();
        }
    }//GEN-LAST:event_textFieldRNEKeyPressed

    private void BuscarRNEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarRNEMouseEntered
        BuscarRNE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Search_24px.png")));
    }//GEN-LAST:event_BuscarRNEMouseEntered

    private void BuscarRNEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarRNEMouseExited
        BuscarRNE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Search_sombrapx.png")));
    }//GEN-LAST:event_BuscarRNEMouseExited

    private void BuscarRNEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarRNEMousePressed
        BuscarRNE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Search_24px.png")));
    }//GEN-LAST:event_BuscarRNEMousePressed

    private void BuscarRNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarRNEActionPerformed

        buscarRNE();
    }//GEN-LAST:event_BuscarRNEActionPerformed

    private
            void buscarRNE() {
        try {

            Establecimiento est = Establecimiento.recuperarPorNroRNE(textFieldRNE.getText());

            if (est != null) {
                Empresa empresa = est.getM_Empresa();
                
             // recupero producto alimenticio Asociado al establecimiento encontrado.
                Vector<ProductoAlimenticio> paAsociados = est.getProductosAsociados();
                
                cargarCampos(est,empresa,paAsociados);
            }
            else {

                resetearCampos();

                JOptionPane.showMessageDialog(null, "No se a encontrado ningun establecimiento con ese numero de RNE");
            }

        }
        catch (SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(panelCargaProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private
            void cargarCampos(Establecimiento est,Empresa empresa,Vector<ProductoAlimenticio> paAsociados){
        try {


            textFieldCUIT.setText(String.valueOf(empresa.getCUIT()));
            textFieldNombreEmpresa.setText(empresa.getNombre());
            textFieldRazonSocial.setText(empresa.getRazon_social());
            textFieldEmailEmpresa.setText(empresa.getEmail());
            textFieldTelefonoEmpresa.setText(String.valueOf(empresa.getTelefono()));
            textFieldRNE.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204), 1));

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            if (est.getFechaDeCarga() != null) {
                textFieldFechaCarga.setText(sdf.format(est.getFechaDeCarga().getTime()));
            }
            else {
                textFieldFechaCarga.setText("");
            }
            textFieldCategoria.setText(est.getNombreCategoria());
            textFieldLocalidad.setText(est.getNombreLocalidad());
            textFieldNombre.setText(est.getNombre());
            textFieldDireccion.setText(est.getDireccion());

            if (est.getRne() != null) {

                if (est.getRne().getFecha_vencimiento() != null)
                    textFieldFVencimientoRNE.setText(sdf.format(est.getRne().getFecha_vencimiento().getTime()));
                else
                    textFieldFVencimientoRNE.setText("");

            }

            if (est.getTelefono() != 0)
                textFieldTelefono.setText(String.valueOf(est.getTelefono()));
            else
                textFieldTelefono.setText("");

            if (est.getNro_factura() != 0)
                textFieldNroFactura.setText(String.valueOf(est.getNro_factura()));
            else {
                textFieldNroFactura.setText("");
            }
            
            // cargo la tabla de Productos alimenticios Asociados.
            cargarTabla(paAsociados);

        }
        catch (SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(panelCargaProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private
            void resetearCampos() {

        textFieldCUIT.setText("");
        textFieldNombreEmpresa.setText("");
        textFieldRazonSocial.setText("");
        textFieldEmailEmpresa.setText("");
        textFieldTelefonoEmpresa.setText("");

        textFieldDireccion.setText("");
        textFieldFVencimientoRNE.setText("");
        textFieldFechaCarga.setText("");
        textFieldCategoria.setText("");
        textFieldLocalidad.setText("");
        textFieldNombre.setText("");
        textFieldNroFactura.setText("");
        textFieldTelefono.setText("");

        LimpiarTabla();

    }
      
    /**
     * esta funcion carga una tabla con los datos de los productos alimenticios.
     *
     * @param ProductosAlimenticios vector de Productos Alimenticios
     */           
    private
            void cargarTabla(Vector<ProductoAlimenticio> ProductosAlimenticios) {

        Object[][] datosDePAAsociados = new Object[ProductosAlimenticios.size()][5];
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (int i = 0; i < ProductosAlimenticios.size(); i++) {
            datosDePAAsociados[i][0] = ProductosAlimenticios.elementAt(i).getRnpa().getNumero();
            datosDePAAsociados[i][1] = ProductosAlimenticios.elementAt(i).getEstablecimiento().getRne().getNumero();
            datosDePAAsociados[i][2] = ProductosAlimenticios.elementAt(i).getComposicion().getNombre_comercial();
            datosDePAAsociados[i][3] = sdf.format(ProductosAlimenticios.elementAt(i).getRnpa().getFecha_vencimiento().getTime());
            datosDePAAsociados[i][4] = ProductosAlimenticios.elementAt(i).getComposicion().getMarca();
        }

        TablaPAAsociado.setModel(new javax.swing.table.DefaultTableModel(
                datosDePAAsociados,
                new String[]{
                    "Numero RNPA", "Numero RNE", "Nombre Producto", "Vencimiento RNPA", "Marca"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };

            public
                    boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

    }
   /**
     * esta funcion limpia la tabla que contiene el panel.
     */
    private
            void LimpiarTabla() {

        TablaPAAsociado.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null},},
                new String[]{
                    "Numero RNPA", "Numero RNE", "Nombre Producto", "Vencimiento RNPA", "Marca"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };

            public
                    boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarRNE;
    private javax.swing.JLabel EtiquetaConsultaPorRNE;
    private javax.swing.JLabel EtiquetaDatosEmpresa;
    private javax.swing.JLabel EtiquetaPAAsociado;
    private javax.swing.JScrollPane ScrollpanelPAAsociado;
    private javax.swing.JSeparator SeparadorDatosEmpresa;
    private javax.swing.JSeparator SeparadorDatosEstablecimiento;
    private javax.swing.JSeparator SeparadorPAAsociado;
    private javax.swing.JTable TablaPAAsociado;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEmp_CUIL;
    private javax.swing.JLabel labelEmp_Email;
    private javax.swing.JLabel labelEmp_NombreEmpresa;
    private javax.swing.JLabel labelEmp_RazonSocial;
    private javax.swing.JLabel labelEmp_Telefono;
    private javax.swing.JLabel labelFVencimientoRNE;
    private javax.swing.JLabel labelFechaCarga;
    private javax.swing.JLabel labelLocalidad;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNroFactura;
    private javax.swing.JLabel labelNumRNE;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel lavelCategoria;
    private javax.swing.JTextField textFieldCUIT;
    private javax.swing.JTextField textFieldCategoria;
    private javax.swing.JTextField textFieldDireccion;
    private javax.swing.JTextField textFieldEmailEmpresa;
    private javax.swing.JTextField textFieldFVencimientoRNE;
    private javax.swing.JTextField textFieldFechaCarga;
    private javax.swing.JTextField textFieldLocalidad;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldNombreEmpresa;
    private javax.swing.JTextField textFieldNroFactura;
    private javax.swing.JTextField textFieldRNE;
    private javax.swing.JTextField textFieldRazonSocial;
    private javax.swing.JTextField textFieldTelefono;
    private javax.swing.JTextField textFieldTelefonoEmpresa;
    // End of variables declaration//GEN-END:variables

}
