/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.CardLayout;

/**
 *
 * @author mauri
 */
public class formPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public formPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        CardLayout card = (CardLayout)panelCard.getLayout();
        card.show(panelCard, "cargaPA");    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        label_TRAMITES = new javax.swing.JLabel();
        label_CONSULTAS = new javax.swing.JLabel();
        label_ESTADISTICAS = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_ConsultaCUIT = new javax.swing.JLabel();
        label_CargaPA = new javax.swing.JLabel();
        panelCard = new javax.swing.JPanel();
        consultaPorCuit1 = new Presentacion.ConsultaPorCuit();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelCargaProducto1 = new Presentacion.panelCargaProducto();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1980, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        panelMenu.setBackground(new java.awt.Color(139, 195, 74));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_TRAMITES.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        label_TRAMITES.setForeground(new java.awt.Color(255, 255, 255));
        label_TRAMITES.setText("TRAMITES");
        label_TRAMITES.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        label_TRAMITES.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelMenu.add(label_TRAMITES, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 140, 30));

        label_CONSULTAS.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        label_CONSULTAS.setForeground(new java.awt.Color(255, 255, 255));
        label_CONSULTAS.setText("CONSULTAS");
        label_CONSULTAS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        label_CONSULTAS.setPreferredSize(new java.awt.Dimension(115, 29));
        label_CONSULTAS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelMenu.add(label_CONSULTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 150, 30));

        label_ESTADISTICAS.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        label_ESTADISTICAS.setForeground(new java.awt.Color(255, 255, 255));
        label_ESTADISTICAS.setText("ESTADISTICAS");
        label_ESTADISTICAS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        label_ESTADISTICAS.setPreferredSize(new java.awt.Dimension(115, 29));
        label_ESTADISTICAS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelMenu.add(label_ESTADISTICAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 180, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo-SA-nuevo-2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        panelMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 3, 140, 110));

        label_ConsultaCUIT.setBackground(new java.awt.Color(255, 255, 255));
        label_ConsultaCUIT.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        label_ConsultaCUIT.setForeground(new java.awt.Color(255, 255, 255));
        label_ConsultaCUIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/atras.png"))); // NOI18N
        label_ConsultaCUIT.setText("Consulta por CUIT");
        label_ConsultaCUIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_ConsultaCUITMouseClicked(evt);
            }
        });
        panelMenu.add(label_ConsultaCUIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        label_CargaPA.setBackground(new java.awt.Color(255, 255, 255));
        label_CargaPA.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        label_CargaPA.setForeground(new java.awt.Color(255, 255, 255));
        label_CargaPA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/atras.png"))); // NOI18N
        label_CargaPA.setText("Cargar producto alimenticio");
        label_CargaPA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_CargaPAMouseClicked(evt);
            }
        });
        panelMenu.add(label_CargaPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        getContentPane().add(panelMenu, java.awt.BorderLayout.PAGE_START);

        panelCard.setLayout(new java.awt.CardLayout());
        panelCard.add(consultaPorCuit1, "consultaCUIT");

        jScrollPane2.setViewportView(panelCargaProducto1);

        panelCard.add(jScrollPane2, "cargaPA");

        getContentPane().add(panelCard, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_CargaPAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_CargaPAMouseClicked
        CardLayout card = (CardLayout)panelCard.getLayout();
        card.show(panelCard, "cargaPA");
        
    }//GEN-LAST:event_label_CargaPAMouseClicked

    private void label_ConsultaCUITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ConsultaCUITMouseClicked
        CardLayout card = (CardLayout)panelCard.getLayout();
        card.show(panelCard, "consultaCUIT");
    }//GEN-LAST:event_label_ConsultaCUITMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new formPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Presentacion.ConsultaPorCuit consultaPorCuit1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_CONSULTAS;
    private javax.swing.JLabel label_CargaPA;
    private javax.swing.JLabel label_ConsultaCUIT;
    private javax.swing.JLabel label_ESTADISTICAS;
    private javax.swing.JLabel label_TRAMITES;
    private javax.swing.JPanel panelCard;
    private Presentacion.panelCargaProducto panelCargaProducto1;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
