/**
 * @author Francisco Herrero, Franco Morero y Mauricio Vazquez
 * @version 1.0
 */
package Presentacion;

import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.ImageIcon;

public class formPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public formPrincipal() {
        initComponents();

        setIconImage(new ImageIcon(getClass().getResource("/resources/icono.png")).getImage());
        this.setLocationRelativeTo(null);
        CardLayout card = (CardLayout) panelCard.getLayout();
        card.show(panelCard, "bienvenido");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        label_TRAMITES = new javax.swing.JLabel();
        label_CONSULTAS = new javax.swing.JLabel();
        label_ESTADISTICAS = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        label_ConsultaCUIT = new javax.swing.JLabel();
        label_CargaPA = new javax.swing.JLabel();
        panelCard = new javax.swing.JPanel();
        panelBienvenida = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ScrollPanelConsultaCUIT = new javax.swing.JScrollPane();
        ScrollPanelConsultaCUIT.getVerticalScrollBar().setUnitIncrement(16);
        consultaPorCuit1 = new Presentacion.ConsultaPorCuit();
        scrollPanelCargaPA = new javax.swing.JScrollPane();
        scrollPanelCargaPA.getVerticalScrollBar().setUnitIncrement(16);
        panelCargaProducto1 = new Presentacion.panelCargaProducto();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de gestion de alimentos - URESA Andina");
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(1000, 500));

        panelMenu.setBackground(new java.awt.Color(139, 195, 74));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_TRAMITES.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        label_TRAMITES.setForeground(new java.awt.Color(255, 255, 255));
        label_TRAMITES.setText("TRAMITES");
        label_TRAMITES.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        label_TRAMITES.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelMenu.add(label_TRAMITES, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 140, 30));

        label_CONSULTAS.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        label_CONSULTAS.setForeground(new java.awt.Color(255, 255, 255));
        label_CONSULTAS.setText("CONSULTAS");
        label_CONSULTAS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        label_CONSULTAS.setPreferredSize(new java.awt.Dimension(115, 29));
        label_CONSULTAS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelMenu.add(label_CONSULTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 150, 30));

        label_ESTADISTICAS.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        label_ESTADISTICAS.setForeground(new java.awt.Color(255, 255, 255));
        label_ESTADISTICAS.setText("ESTADISTICAS");
        label_ESTADISTICAS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        label_ESTADISTICAS.setPreferredSize(new java.awt.Dimension(115, 29));
        label_ESTADISTICAS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelMenu.add(label_ESTADISTICAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 180, 30));

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logomarcarn.png"))); // NOI18N
        panelMenu.add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 110));

        label_ConsultaCUIT.setBackground(new java.awt.Color(255, 255, 255));
        label_ConsultaCUIT.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        label_ConsultaCUIT.setForeground(new java.awt.Color(255, 255, 255));
        label_ConsultaCUIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/atras.png"))); // NOI18N
        label_ConsultaCUIT.setText("Consulta por CUIT");
        label_ConsultaCUIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_ConsultaCUITMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_ConsultaCUITMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_ConsultaCUITMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_ConsultaCUITMouseReleased(evt);
            }
        });
        panelMenu.add(label_ConsultaCUIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        label_CargaPA.setBackground(new java.awt.Color(255, 255, 255));
        label_CargaPA.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        label_CargaPA.setForeground(new java.awt.Color(255, 255, 255));
        label_CargaPA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/atras.png"))); // NOI18N
        label_CargaPA.setText("Cargar producto alimenticio");
        label_CargaPA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_CargaPAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_CargaPAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_CargaPAMouseExited(evt);
            }
        });
        panelMenu.add(label_CargaPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        getContentPane().add(panelMenu, java.awt.BorderLayout.PAGE_START);

        panelCard.setLayout(new java.awt.CardLayout());

        panelBienvenida.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccione una opcion para comenzar");

        javax.swing.GroupLayout panelBienvenidaLayout = new javax.swing.GroupLayout(panelBienvenida);
        panelBienvenida.setLayout(panelBienvenidaLayout);
        panelBienvenidaLayout.setHorizontalGroup(
            panelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
        );
        panelBienvenidaLayout.setVerticalGroup(
            panelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBienvenidaLayout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        panelCard.add(panelBienvenida, "bienvenida");

        ScrollPanelConsultaCUIT.setViewportView(consultaPorCuit1);

        panelCard.add(ScrollPanelConsultaCUIT, "consultaCUIT");

        scrollPanelCargaPA.setBorder(null);
        scrollPanelCargaPA.setViewportView(panelCargaProducto1);

        panelCard.add(scrollPanelCargaPA, "cargaPA");

        getContentPane().add(panelCard, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_CargaPAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_CargaPAMouseClicked
        CardLayout card = (CardLayout) panelCard.getLayout();
        card.show(panelCard, "cargaPA");

    }//GEN-LAST:event_label_CargaPAMouseClicked

    private void label_ConsultaCUITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ConsultaCUITMouseClicked
        CardLayout card = (CardLayout) panelCard.getLayout();
        card.show(panelCard, "consultaCUIT");
    }//GEN-LAST:event_label_ConsultaCUITMouseClicked

    private void label_CargaPAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_CargaPAMouseEntered
        label_CargaPA.setFont(new Font("Roboto", Font.BOLD, 13));
    }//GEN-LAST:event_label_CargaPAMouseEntered

    private void label_CargaPAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_CargaPAMouseExited
        label_CargaPA.setFont(new Font("Roboto", Font.BOLD, 12));
    }//GEN-LAST:event_label_CargaPAMouseExited

    private void label_ConsultaCUITMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ConsultaCUITMouseEntered
        label_ConsultaCUIT.setFont(new Font("Roboto", Font.BOLD, 13));
    }//GEN-LAST:event_label_ConsultaCUITMouseEntered

    private void label_ConsultaCUITMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ConsultaCUITMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_ConsultaCUITMouseReleased

    private void label_ConsultaCUITMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ConsultaCUITMouseExited
        label_ConsultaCUIT.setFont(new Font("Roboto", Font.BOLD, 12));
    }//GEN-LAST:event_label_ConsultaCUITMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new formPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPanelConsultaCUIT;
    private Presentacion.ConsultaPorCuit consultaPorCuit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel label_CONSULTAS;
    private javax.swing.JLabel label_CargaPA;
    private javax.swing.JLabel label_ConsultaCUIT;
    private javax.swing.JLabel label_ESTADISTICAS;
    private javax.swing.JLabel label_TRAMITES;
    private javax.swing.JPanel panelBienvenida;
    private javax.swing.JPanel panelCard;
    private Presentacion.panelCargaProducto panelCargaProducto1;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JScrollPane scrollPanelCargaPA;
    // End of variables declaration//GEN-END:variables
}
