/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco
 */
public class panelCargaProducto extends javax.swing.JPanel {

    /**
     * Creates new form CargaProducto
     */
    public panelCargaProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCargaPA = new javax.swing.JTabbedPane();
        CargaBasicaScroll = new javax.swing.JScrollPane();
        CargaBasica = new javax.swing.JPanel();
        NumRNE = new javax.swing.JLabel();
        TextFieldRNE = new javax.swing.JTextField();
        BuscarRNE = new javax.swing.JButton();
        SeparadorDatosEmpresa = new javax.swing.JSeparator();
        EtiquetaTituloDatoEmpresa = new javax.swing.JLabel();
        EtiquetaCUIL = new javax.swing.JLabel();
        EtiquetaNombreEmpresa = new javax.swing.JLabel();
        EtiquetaRazonSocial = new javax.swing.JLabel();
        EtiquetaEmail = new javax.swing.JLabel();
        EtiquetaTelefono = new javax.swing.JLabel();
        CampoCUIL = new javax.swing.JTextField();
        CampoNombreEmpresa = new javax.swing.JTextField();
        CampoRazonSocial = new javax.swing.JTextField();
        CampoEmail = new javax.swing.JTextField();
        CampoTelefono = new javax.swing.JTextField();
        SeparadorRegistroRNPA = new javax.swing.JSeparator();
        EtiquetaDatosPA = new javax.swing.JLabel();
        EtiquetaNroFactura = new javax.swing.JLabel();
        CampoNroFactura = new javax.swing.JTextField();
        SeparadorDatosProducto = new javax.swing.JSeparator();
        EtiquetaRegistroRNPA = new javax.swing.JLabel();
        EtiquetaRNPA = new javax.swing.JLabel();
        CampoRNPA = new javax.swing.JTextField();
        CampoFechaVencimiento = new javax.swing.JFormattedTextField();
        EtiquetaFechaVencimiento = new javax.swing.JLabel();
        EtiquetaRotulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CampoRotulo = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        EtiquetaDatosDeLab = new javax.swing.JLabel();
        EtiquetaCargaProdAlimenticio = new javax.swing.JLabel();
        EtiquetaNumProtocolo = new javax.swing.JLabel();
        CampoNumProtocolo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        CargaComposicionScroll = new javax.swing.JScrollPane();
        CargaComposicion = new javax.swing.JPanel();
        CargaDescripcionScroll = new javax.swing.JScrollPane();
        CargaDescripcion = new javax.swing.JPanel();

        PanelCargaPA.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                PanelCargaPAComponentAdded(evt);
            }
        });

        NumRNE.setText("Numero RNE: ");

        TextFieldRNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldRNEActionPerformed(evt);
            }
        });

        BuscarRNE.setText("Buscar");
        BuscarRNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarRNEActionPerformed(evt);
            }
        });

        EtiquetaTituloDatoEmpresa.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        EtiquetaTituloDatoEmpresa.setText("Datos de la empresa");

        EtiquetaCUIL.setText("CUIT: ");

        EtiquetaNombreEmpresa.setText("Nombre: ");

        EtiquetaRazonSocial.setText("Razon Social: ");

        EtiquetaEmail.setText("Email: ");

        EtiquetaTelefono.setText("Telefono: ");

        CampoCUIL.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        CampoCUIL.setText("2345678");
        CampoCUIL.setEnabled(false);

        CampoNombreEmpresa.setEnabled(false);

        CampoRazonSocial.setEnabled(false);

        CampoEmail.setEnabled(false);
        CampoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEmailActionPerformed(evt);
            }
        });

        CampoTelefono.setEnabled(false);

        EtiquetaDatosPA.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        EtiquetaDatosPA.setText("Datos del producto alimenticio");

        EtiquetaNroFactura.setText("Nro factura: ");

        EtiquetaRegistroRNPA.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        EtiquetaRegistroRNPA.setText("Registro numero RNPA");

        EtiquetaRNPA.setText("RNPA: ");

        CampoFechaVencimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        EtiquetaFechaVencimiento.setText("Fecha Vencimiento: ");

        EtiquetaRotulo.setText("Rotulo: ");

        CampoRotulo.setColumns(20);
        CampoRotulo.setRows(5);
        jScrollPane1.setViewportView(CampoRotulo);

        EtiquetaDatosDeLab.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        EtiquetaDatosDeLab.setText("Datos de la muestra de laboratorio");

        EtiquetaCargaProdAlimenticio.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        EtiquetaCargaProdAlimenticio.setText("Carga de Producto Alimenticio");

        EtiquetaNumProtocolo.setText("Numero Protocolo: ");

        jLabel1.setText("Numero de Acta: ");

        javax.swing.GroupLayout CargaBasicaLayout = new javax.swing.GroupLayout(CargaBasica);
        CargaBasica.setLayout(CargaBasicaLayout);
        CargaBasicaLayout.setHorizontalGroup(
            CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CargaBasicaLayout.createSequentialGroup()
                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CargaBasicaLayout.createSequentialGroup()
                        .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CargaBasicaLayout.createSequentialGroup()
                                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CargaBasicaLayout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(EtiquetaTituloDatoEmpresa))
                                    .addGroup(CargaBasicaLayout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(NumRNE, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextFieldRNE, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BuscarRNE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(CargaBasicaLayout.createSequentialGroup()
                                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CargaBasicaLayout.createSequentialGroup()
                                        .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(CargaBasicaLayout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(EtiquetaDatosPA))
                                            .addGroup(CargaBasicaLayout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(EtiquetaRegistroRNPA))
                                            .addGroup(CargaBasicaLayout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(EtiquetaRotulo)
                                                    .addGroup(CargaBasicaLayout.createSequentialGroup()
                                                        .addComponent(EtiquetaNroFactura)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(CampoNroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(80, 80, 80))
                                    .addGroup(CargaBasicaLayout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(EtiquetaRNPA, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CampoRNPA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EtiquetaFechaVencimiento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(CampoFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SeparadorDatosEmpresa)
                            .addGroup(CargaBasicaLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CampoNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EtiquetaCUIL)
                                        .addComponent(EtiquetaNombreEmpresa)
                                        .addComponent(EtiquetaRazonSocial)
                                        .addComponent(CampoCUIL, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CampoRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(CargaBasicaLayout.createSequentialGroup()
                                        .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EtiquetaTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(EtiquetaEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(142, 142, 142))
                                    .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CampoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(30, 30, 30))
                    .addComponent(jSeparator1)
                    .addComponent(SeparadorDatosProducto)
                    .addComponent(SeparadorRegistroRNPA, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CargaBasicaLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EtiquetaDatosDeLab)
                            .addGroup(CargaBasicaLayout.createSequentialGroup()
                                .addComponent(EtiquetaNumProtocolo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoNumProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
            .addGroup(CargaBasicaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(EtiquetaCargaProdAlimenticio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CargaBasicaLayout.setVerticalGroup(
            CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CargaBasicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaCargaProdAlimenticio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumRNE)
                    .addComponent(BuscarRNE)
                    .addComponent(TextFieldRNE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(SeparadorDatosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EtiquetaTituloDatoEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaCUIL)
                    .addComponent(EtiquetaEmail))
                .addGap(5, 5, 5)
                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoCUIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaNombreEmpresa)
                    .addComponent(EtiquetaTelefono))
                .addGap(4, 4, 4)
                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EtiquetaRazonSocial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeparadorRegistroRNPA, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EtiquetaRegistroRNPA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaRNPA)
                    .addComponent(CampoRNPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtiquetaFechaVencimiento))
                .addGap(24, 24, 24)
                .addComponent(SeparadorDatosProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EtiquetaDatosPA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtiquetaNroFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EtiquetaRotulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EtiquetaDatosDeLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CargaBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaNumProtocolo)
                    .addComponent(CampoNumProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        CargaBasicaScroll.setViewportView(CargaBasica);

        PanelCargaPA.addTab("Informacion General", CargaBasicaScroll);

        javax.swing.GroupLayout CargaComposicionLayout = new javax.swing.GroupLayout(CargaComposicion);
        CargaComposicion.setLayout(CargaComposicionLayout);
        CargaComposicionLayout.setHorizontalGroup(
            CargaComposicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );
        CargaComposicionLayout.setVerticalGroup(
            CargaComposicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        CargaComposicionScroll.setViewportView(CargaComposicion);

        PanelCargaPA.addTab("Composicion", CargaComposicionScroll);

        javax.swing.GroupLayout CargaDescripcionLayout = new javax.swing.GroupLayout(CargaDescripcion);
        CargaDescripcion.setLayout(CargaDescripcionLayout);
        CargaDescripcionLayout.setHorizontalGroup(
            CargaDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );
        CargaDescripcionLayout.setVerticalGroup(
            CargaDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        CargaDescripcionScroll.setViewportView(CargaDescripcion);

        PanelCargaPA.addTab("Descripcion", CargaDescripcionScroll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCargaPA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCargaPA, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldRNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldRNEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldRNEActionPerformed

    private void BuscarRNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarRNEActionPerformed
        try {
            Empresa empresa = recuperarDatosEmpresa(TextFieldRNE.getText());
            if (empresa != null) {
                CampoCUIL.setText(String.valueOf(empresa.getCUIT()));
                CampoNombreEmpresa.setText(empresa.getNombre());
                CampoRazonSocial.setText(empresa.getRazon_social());
                CampoEmail.setText(empresa.getEmail());
                CampoTelefono.setText(String.valueOf(empresa.getTelefono()));
            } else {
                JOptionPane.showMessageDialog(null, "Numero RNE no encontrado.");
            }
        } catch (SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(panelCargaProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BuscarRNEActionPerformed

    private void CampoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEmailActionPerformed

    private void PanelCargaPAComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_PanelCargaPAComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelCargaPAComponentAdded

    private Empresa recuperarDatosEmpresa(String nro_rne) throws SQLException, InstantiationException, IllegalAccessException {
        Empresa empresa_salida = null;
        try {
            Establecimiento estab = Establecimiento.recuperarPorNroRNE(nro_rne);
            if (estab != null) {
                empresa_salida = Empresa.recuperarPorCuit(String.valueOf(estab.getCUIT_Empresa()));
            }

        } catch (SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Establecimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        return empresa_salida;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarRNE;
    private javax.swing.JTextField CampoCUIL;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JFormattedTextField CampoFechaVencimiento;
    private javax.swing.JTextField CampoNombreEmpresa;
    private javax.swing.JTextField CampoNroFactura;
    private javax.swing.JTextField CampoNumProtocolo;
    private javax.swing.JTextField CampoRNPA;
    private javax.swing.JTextField CampoRazonSocial;
    private javax.swing.JTextArea CampoRotulo;
    private javax.swing.JTextField CampoTelefono;
    private javax.swing.JPanel CargaBasica;
    private javax.swing.JScrollPane CargaBasicaScroll;
    private javax.swing.JPanel CargaComposicion;
    private javax.swing.JScrollPane CargaComposicionScroll;
    private javax.swing.JPanel CargaDescripcion;
    private javax.swing.JScrollPane CargaDescripcionScroll;
    private javax.swing.JLabel EtiquetaCUIL;
    private javax.swing.JLabel EtiquetaCargaProdAlimenticio;
    private javax.swing.JLabel EtiquetaDatosDeLab;
    private javax.swing.JLabel EtiquetaDatosPA;
    private javax.swing.JLabel EtiquetaEmail;
    private javax.swing.JLabel EtiquetaFechaVencimiento;
    private javax.swing.JLabel EtiquetaNombreEmpresa;
    private javax.swing.JLabel EtiquetaNroFactura;
    private javax.swing.JLabel EtiquetaNumProtocolo;
    private javax.swing.JLabel EtiquetaRNPA;
    private javax.swing.JLabel EtiquetaRazonSocial;
    private javax.swing.JLabel EtiquetaRegistroRNPA;
    private javax.swing.JLabel EtiquetaRotulo;
    private javax.swing.JLabel EtiquetaTelefono;
    private javax.swing.JLabel EtiquetaTituloDatoEmpresa;
    private javax.swing.JLabel NumRNE;
    private javax.swing.JTabbedPane PanelCargaPA;
    private javax.swing.JSeparator SeparadorDatosEmpresa;
    private javax.swing.JSeparator SeparadorDatosProducto;
    private javax.swing.JSeparator SeparadorRegistroRNPA;
    private javax.swing.JTextField TextFieldRNE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
