/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Franco
 */
public class panelEstadisticasPorcentajexRubro extends javax.swing.JPanel {

    /**
     * Creates new form panelEstadisticasPorcentajexRubro
     */
    public panelEstadisticasPorcentajexRubro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPorcentajexRubro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPorcentajexRubro.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        labelPorcentajexRubro.setForeground(new java.awt.Color(0, 51, 0));
        labelPorcentajexRubro.setText("Porcentaje por rubro");
        add(labelPorcentajexRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 20, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 57, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PorcentajexRubro observado;
        try {
            observado = new PorcentajexRubro();
            GraficoTorta observador;
            observador = new GraficoTorta();

            observado.addObserver(observador);

            observado.actualizarEstado();
            observado.actualizarEstado();
        } catch (SQLException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(panelEstadisticasPorcentajexRubro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelPorcentajexRubro;
    // End of variables declaration//GEN-END:variables
}
