/**
 * @author Francisco Herrero, Franco Morero y Mauricio Vazquez
 * @version 1.0
 */
package Presentacion;

import Logica.Envase;
import java.awt.Component;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

public class panelCargaEnvase extends javax.swing.JPanel {

    /**
     * Creates new form panelEnvase
     */
    public panelCargaEnvase() {
        initComponents();
        createComponentMap();
        cargarValores();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCapacidad = new javax.swing.JLabel();
        textFieldCapacidad = new javax.swing.JTextField();
        comboBoxMaterial = new javax.swing.JComboBox<>();
        labelMaterial = new javax.swing.JLabel();
        labelUnidad = new javax.swing.JLabel();
        comboBoxUnidad = new javax.swing.JComboBox<>();
        buttonAddCapacidad = new javax.swing.JButton();
        buttonAddUnidad = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(521, 35));
        setMinimumSize(new java.awt.Dimension(521, 35));
        setPreferredSize(new java.awt.Dimension(521, 35));

        labelCapacidad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelCapacidad.setText("Capacidad:");
        labelCapacidad.setName("labelCapacidad"); // NOI18N

        textFieldCapacidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        textFieldCapacidad.setName("textFieldCapacidad"); // NOI18N
        textFieldCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCapacidadActionPerformed(evt);
            }
        });

        comboBoxMaterial.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        comboBoxMaterial.setForeground(new java.awt.Color(76, 140, 74));
        comboBoxMaterial.setMaximumRowCount(16);
        comboBoxMaterial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboBoxMaterial.setName("comboBoxMaterial"); // NOI18N
        comboBoxMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMaterialActionPerformed(evt);
            }
        });

        labelMaterial.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelMaterial.setText("Material");
        labelMaterial.setName("labelMaterial"); // NOI18N

        labelUnidad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelUnidad.setText("Unidad:");
        labelUnidad.setName("labelUnidad"); // NOI18N

        comboBoxUnidad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        comboBoxUnidad.setForeground(new java.awt.Color(76, 140, 74));
        comboBoxUnidad.setMaximumRowCount(16);
        comboBoxUnidad.setName("comboBoxUnidad"); // NOI18N

        buttonAddCapacidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mas.png"))); // NOI18N
        buttonAddCapacidad.setBorder(null);
        buttonAddCapacidad.setBorderPainted(false);
        buttonAddCapacidad.setContentAreaFilled(false);
        buttonAddCapacidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAddCapacidadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonAddCapacidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonAddCapacidadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonAddCapacidadMousePressed(evt);
            }
        });

        buttonAddUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mas.png"))); // NOI18N
        buttonAddUnidad.setBorder(null);
        buttonAddUnidad.setBorderPainted(false);
        buttonAddUnidad.setContentAreaFilled(false);
        buttonAddUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAddUnidadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonAddUnidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonAddUnidadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonAddUnidadMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelCapacidad)
                .addGap(6, 6, 6)
                .addComponent(textFieldCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelMaterial)
                .addGap(2, 2, 2)
                .addComponent(comboBoxMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAddCapacidad)
                .addGap(28, 28, 28)
                .addComponent(labelUnidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAddUnidad)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxMaterial)
                            .addComponent(buttonAddCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonAddUnidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textFieldCapacidad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCapacidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCapacidadActionPerformed

    private void comboBoxMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMaterialActionPerformed

    private void buttonAddCapacidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddCapacidadMouseEntered
        buttonAddCapacidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mas_entered.png")));
    }//GEN-LAST:event_buttonAddCapacidadMouseEntered

    private void buttonAddCapacidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddCapacidadMouseExited
        buttonAddCapacidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mas.png")));
    }//GEN-LAST:event_buttonAddCapacidadMouseExited

    private void buttonAddUnidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddUnidadMouseEntered
        buttonAddUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mas_entered.png")));
    }//GEN-LAST:event_buttonAddUnidadMouseEntered

    private void buttonAddUnidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddUnidadMouseExited
        buttonAddUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mas.png")));
    }//GEN-LAST:event_buttonAddUnidadMouseExited

    private void buttonAddCapacidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddCapacidadMouseClicked
        buttonAddCapacidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mas_entered.png")));
    }//GEN-LAST:event_buttonAddCapacidadMouseClicked

    private void buttonAddUnidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddUnidadMouseClicked
        buttonAddUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mas_entered.png")));
    }//GEN-LAST:event_buttonAddUnidadMouseClicked

    private void buttonAddCapacidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddCapacidadMousePressed
        buttonAddCapacidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mas_pressed.png")));
    }//GEN-LAST:event_buttonAddCapacidadMousePressed

    private void buttonAddUnidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddUnidadMousePressed
        buttonAddUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mas_pressed.png")));
    }//GEN-LAST:event_buttonAddUnidadMousePressed

    private void createComponentMap() {
        componentMap = new HashMap<>();
        Component[] components;
        components = this.getComponents();
        for (Component component : components) {
            componentMap.put(component.getName(), component);
        }
    }

    public Component getComponentByName(String name) {
        if (componentMap.containsKey(name)) {
            return (Component) componentMap.get(name);
        } else {
            return null;
        }
    }

    private void cargarValores() {
        // TODO add your handling code here:
        Vector<String> mat_uni;
        Vector<String> mat_car;

        try {
            mat_uni = Envase.recuperarTodosUnidades();
            for (int i = 0; i < mat_uni.size(); i++) {
                comboBoxUnidad.addItem(mat_uni.elementAt(i));
            }
            mat_car = Envase.recuperarTodosMateriales();
            for (int j = 0; j < mat_car.size(); j++) {
                comboBoxMaterial.addItem(mat_car.elementAt(j));
            }
        } catch (SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(panelCargaEnvase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private HashMap componentMap;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddCapacidad;
    private javax.swing.JButton buttonAddUnidad;
    private javax.swing.JComboBox<String> comboBoxMaterial;
    private javax.swing.JComboBox<String> comboBoxUnidad;
    private javax.swing.JLabel labelCapacidad;
    private javax.swing.JLabel labelMaterial;
    private javax.swing.JLabel labelUnidad;
    private javax.swing.JTextField textFieldCapacidad;
    // End of variables declaration//GEN-END:variables
}
