/**
 * @author Francisco Herrero, Franco Morero y Mauricio Vazquez
 * @version 1.0
 */
package Presentacion;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class panelEstadisticasPorcentajexRubro extends javax.swing.JPanel {

    /**
     * Creates new form CargaProducto
     */
    public panelEstadisticasPorcentajexRubro() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        labelPorcentajexRubro = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));

        labelPorcentajexRubro.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        labelPorcentajexRubro.setForeground(new java.awt.Color(0, 51, 0));
        labelPorcentajexRubro.setText("Porcentaje por rubro ");
        add(labelPorcentajexRubro);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PorcentajexRubro observado;
        try {
            observado = new PorcentajexRubro();
            GraficoTorta observador;
            observador = new GraficoTorta();

            observado.addObserver(observador);

            observado.actualizarEstado();
            observado.actualizarEstado();
        } catch (SQLException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(panelEstadisticasPorcentajexRubro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel labelPorcentajexRubro;
    // End of variables declaration//GEN-END:variables
}
