/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco
 */
public class panelCargaProducto extends javax.swing.JPanel {

    /**
     * Creates new form CargaProducto
     */
    public panelCargaProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CargaBasica = new javax.swing.JPanel();
        labelNumRNE = new javax.swing.JLabel();
        textFieldRNE = new javax.swing.JTextField();
        BuscarRNE = new javax.swing.JButton();
        SeparadorDatosEmpresa = new javax.swing.JSeparator();
        labelDatoEmpresa = new javax.swing.JLabel();
        labelEmp_CUIL = new javax.swing.JLabel();
        labelEmp_NombreEmpresa = new javax.swing.JLabel();
        labelEmp_RazonSocial = new javax.swing.JLabel();
        labelEmp_Email = new javax.swing.JLabel();
        labelEmp_Telefono = new javax.swing.JLabel();
        textFieldEmp_CUIL = new javax.swing.JTextField();
        textFieldEmp_Nombre = new javax.swing.JTextField();
        textFieldEmp_RazonSocial = new javax.swing.JTextField();
        textFieldEmp_Email = new javax.swing.JTextField();
        textFieldEmp_Telefono = new javax.swing.JTextField();
        SeparadorRegistroRNPA = new javax.swing.JSeparator();
        labelComposicion = new javax.swing.JLabel();
        labelNroFactura = new javax.swing.JLabel();
        textFieldNroFactura = new javax.swing.JTextField();
        SeparadorDatosProducto = new javax.swing.JSeparator();
        labelRegistroRNPA = new javax.swing.JLabel();
        labelRNPA = new javax.swing.JLabel();
        textFieldRNPA = new javax.swing.JTextField();
        textFieldFechaVencimiento = new javax.swing.JFormattedTextField();
        labelFechaVencimiento = new javax.swing.JLabel();
        labelRotulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaRotulo = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        labelDatosDeLab = new javax.swing.JLabel();
        labelCargaProdAlimenticio = new javax.swing.JLabel();
        labelNumProtocolo = new javax.swing.JLabel();
        textFieldNroProtocolo = new javax.swing.JTextField();
        labelNroActa = new javax.swing.JLabel();
        textFieldNroActa = new javax.swing.JTextField();
        SeparadorRegistroRNPA1 = new javax.swing.JSeparator();
        labelComp_Nombre = new javax.swing.JLabel();
        labelComp_Marca = new javax.swing.JLabel();
        labelComp_Denominacion = new javax.swing.JLabel();
        labelComp_Contenido = new javax.swing.JLabel();
        labelComp_FechaDuracion = new javax.swing.JLabel();
        labelComp_NroTipoMarca = new javax.swing.JLabel();
        labelComp_CAA = new javax.swing.JLabel();
        labelComp_MateriasPrimas = new javax.swing.JLabel();
        textFieldComp_Nombre = new javax.swing.JTextField();
        textFieldComp_Marca = new javax.swing.JTextField();
        textFieldComp_Denominacion = new javax.swing.JTextField();
        textFieldComp_Contenido = new javax.swing.JTextField();
        textFieldComp_FechaDuracion = new javax.swing.JTextField();
        textFieldComp_NroTipoMarca = new javax.swing.JTextField();
        textFieldComp_CAA = new javax.swing.JTextField();
        SeparadorDatosProducto1 = new javax.swing.JSeparator();
        labelDatosPA = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        SeparadorDatosProducto3 = new javax.swing.JSeparator();
        labelDesc_FormaUso = new javax.swing.JLabel();
        labelDesc_PeridoAptitud = new javax.swing.JLabel();
        labelDesc_ModoConservacion = new javax.swing.JLabel();
        labelDesc_DondeVendido = new javax.swing.JLabel();
        labelDesc_InstruccionPrep = new javax.swing.JLabel();
        labelDesc_ControlesEspeciales2 = new javax.swing.JLabel();
        labelDesc_InfoAdicional = new javax.swing.JLabel();
        labelDesc_CaracteristicasEnvase = new javax.swing.JLabel();
        textFieldDesc_FormaUso = new javax.swing.JTextField();
        textFieldDesc_PeriodoAptitud = new javax.swing.JTextField();
        textFieldDesc_ModoConservacion = new javax.swing.JTextField();
        textFieldDesc_DondeVendido = new javax.swing.JTextField();
        textFieldDesc_InstruccionPrep = new javax.swing.JTextField();
        textFieldDesc_ControlesEspeciales = new javax.swing.JTextField();
        textFieldDesc_InfoAdicional = new javax.swing.JTextField();
        labelDesc_AQuienDirigido = new javax.swing.JLabel();
        labelDesc_ControlesEspeciales1 = new javax.swing.JLabel();
        textFieldDesc_AQuienDirigido = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();

        CargaBasica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNumRNE.setText("Numero RNE: ");
        CargaBasica.add(labelNumRNE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 88, 20));

        textFieldRNE.setText("32132132");
        textFieldRNE.setToolTipText("");
        textFieldRNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldRNEActionPerformed(evt);
            }
        });
        CargaBasica.add(textFieldRNE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 171, -1));

        BuscarRNE.setText("Buscar");
        BuscarRNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarRNEActionPerformed(evt);
            }
        });
        CargaBasica.add(BuscarRNE, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));
        CargaBasica.add(SeparadorDatosEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 620, 0));

        labelDatoEmpresa.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        labelDatoEmpresa.setText("Datos de la empresa");
        CargaBasica.add(labelDatoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        labelEmp_CUIL.setText("CUIT: ");
        CargaBasica.add(labelEmp_CUIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        labelEmp_NombreEmpresa.setText("Nombre: ");
        CargaBasica.add(labelEmp_NombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 20));

        labelEmp_RazonSocial.setText("Razon Social: ");
        CargaBasica.add(labelEmp_RazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 20));

        labelEmp_Email.setText("Email: ");
        CargaBasica.add(labelEmp_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 49, 20));

        labelEmp_Telefono.setText("Telefono: ");
        CargaBasica.add(labelEmp_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, 20));

        textFieldEmp_CUIL.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        textFieldEmp_CUIL.setText("2345678");
        textFieldEmp_CUIL.setEnabled(false);
        CargaBasica.add(textFieldEmp_CUIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 122, -1));

        textFieldEmp_Nombre.setEnabled(false);
        CargaBasica.add(textFieldEmp_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 122, -1));

        textFieldEmp_RazonSocial.setEnabled(false);
        CargaBasica.add(textFieldEmp_RazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 122, -1));

        textFieldEmp_Email.setEnabled(false);
        textFieldEmp_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmp_EmailActionPerformed(evt);
            }
        });
        CargaBasica.add(textFieldEmp_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 124, -1));

        textFieldEmp_Telefono.setEnabled(false);
        CargaBasica.add(textFieldEmp_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 124, -1));
        CargaBasica.add(SeparadorRegistroRNPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 690, 10));

        labelComposicion.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        labelComposicion.setText("Composicion");
        CargaBasica.add(labelComposicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, 20));

        labelNroFactura.setText("Nro factura: ");
        CargaBasica.add(labelNroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, 20));

        textFieldNroFactura.setText("123");
        CargaBasica.add(textFieldNroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 120, -1));
        CargaBasica.add(SeparadorDatosProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 670, 10));

        labelRegistroRNPA.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        labelRegistroRNPA.setText("Registro numero RNPA");
        CargaBasica.add(labelRegistroRNPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        labelRNPA.setText("RNPA: ");
        CargaBasica.add(labelRNPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 50, 20));

        textFieldRNPA.setText("123456");
        CargaBasica.add(textFieldRNPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 120, -1));

        textFieldFechaVencimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        CargaBasica.add(textFieldFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 122, -1));

        labelFechaVencimiento.setText("Fecha Vencimiento: ");
        CargaBasica.add(labelFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, 20));

        labelRotulo.setText("Rotulo: ");
        CargaBasica.add(labelRotulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        textAreaRotulo.setColumns(20);
        textAreaRotulo.setRows(5);
        textAreaRotulo.setText("rotulo");
        jScrollPane1.setViewportView(textAreaRotulo);

        CargaBasica.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 560, 70));
        CargaBasica.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1180, 690, 10));

        labelDatosDeLab.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        labelDatosDeLab.setText("Datos de la muestra de laboratorio");
        CargaBasica.add(labelDatosDeLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1200, -1, -1));

        labelCargaProdAlimenticio.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        labelCargaProdAlimenticio.setText("Carga de Producto Alimenticio");
        CargaBasica.add(labelCargaProdAlimenticio, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 11, -1, -1));

        labelNumProtocolo.setText("Numero Protocolo: ");
        CargaBasica.add(labelNumProtocolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1230, -1, 20));
        CargaBasica.add(textFieldNroProtocolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1230, 110, -1));

        labelNroActa.setText("Numero de Acta: ");
        CargaBasica.add(labelNroActa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1230, -1, 20));
        CargaBasica.add(textFieldNroActa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 1230, 116, -1));
        CargaBasica.add(SeparadorRegistroRNPA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 690, 10));

        labelComp_Nombre.setText("Nombre comercial:");
        CargaBasica.add(labelComp_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, 20));

        labelComp_Marca.setText("Marca:");
        CargaBasica.add(labelComp_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, 20));

        labelComp_Denominacion.setText("Denominacion:");
        CargaBasica.add(labelComp_Denominacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, 20));

        labelComp_Contenido.setText("Contenido:");
        CargaBasica.add(labelComp_Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, 20));

        labelComp_FechaDuracion.setText("Fecha de duracion:");
        CargaBasica.add(labelComp_FechaDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, -1, 20));

        labelComp_NroTipoMarca.setText("N° y tipo de registro de marca:");
        CargaBasica.add(labelComp_NroTipoMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, -1, 20));

        labelComp_CAA.setText("CAA Articulo N°:");
        CargaBasica.add(labelComp_CAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, -1, 20));

        labelComp_MateriasPrimas.setText("Materias Primas");
        CargaBasica.add(labelComp_MateriasPrimas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, -1, 20));

        textFieldComp_Nombre.setText("nombre");
        textFieldComp_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldComp_NombreActionPerformed(evt);
            }
        });
        CargaBasica.add(textFieldComp_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 160, -1));

        textFieldComp_Marca.setText("marca");
        CargaBasica.add(textFieldComp_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 160, -1));

        textFieldComp_Denominacion.setText("denominacion");
        CargaBasica.add(textFieldComp_Denominacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 160, -1));

        textFieldComp_Contenido.setText("contenido");
        CargaBasica.add(textFieldComp_Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 160, 20));
        CargaBasica.add(textFieldComp_FechaDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 160, -1));

        textFieldComp_NroTipoMarca.setText("tipomarca");
        CargaBasica.add(textFieldComp_NroTipoMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 160, -1));

        textFieldComp_CAA.setText("caa");
        textFieldComp_CAA.setToolTipText("");
        CargaBasica.add(textFieldComp_CAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 160, -1));
        CargaBasica.add(SeparadorDatosProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 690, 10));

        labelDatosPA.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        labelDatosPA.setText("Datos del producto alimenticio");
        CargaBasica.add(labelDatosPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        labelDescripcion.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        labelDescripcion.setText("Descripcion");
        CargaBasica.add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 760, -1, 20));
        CargaBasica.add(SeparadorDatosProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 790, 670, 10));

        labelDesc_FormaUso.setText("Forma de uso del producto:");
        CargaBasica.add(labelDesc_FormaUso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 810, -1, 20));

        labelDesc_PeridoAptitud.setText("Periodo de aptitud:");
        CargaBasica.add(labelDesc_PeridoAptitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 840, -1, 20));

        labelDesc_ModoConservacion.setText("Modo de conservacion:");
        CargaBasica.add(labelDesc_ModoConservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 870, -1, 20));

        labelDesc_DondeVendido.setText("Donde será vendido el producto:");
        CargaBasica.add(labelDesc_DondeVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 900, -1, 20));

        labelDesc_InstruccionPrep.setText("Instrucciones de preparación:");
        CargaBasica.add(labelDesc_InstruccionPrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 930, -1, 20));

        labelDesc_ControlesEspeciales2.setText("durante la distribución y la comercialización:");
        CargaBasica.add(labelDesc_ControlesEspeciales2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 980, 230, 20));

        labelDesc_InfoAdicional.setText("Información adicional:");
        CargaBasica.add(labelDesc_InfoAdicional, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1040, -1, 20));

        labelDesc_CaracteristicasEnvase.setText("Caracteristicas del envase");
        CargaBasica.add(labelDesc_CaracteristicasEnvase, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1080, -1, 20));

        textFieldDesc_FormaUso.setText("formauso");
        textFieldDesc_FormaUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDesc_FormaUsoActionPerformed(evt);
            }
        });
        CargaBasica.add(textFieldDesc_FormaUso, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 810, 410, -1));

        textFieldDesc_PeriodoAptitud.setText("aptitud");
        CargaBasica.add(textFieldDesc_PeriodoAptitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 840, 410, -1));

        textFieldDesc_ModoConservacion.setText("conservacion");
        CargaBasica.add(textFieldDesc_ModoConservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 870, 410, -1));

        textFieldDesc_DondeVendido.setText("donde");
        CargaBasica.add(textFieldDesc_DondeVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 900, 410, 20));

        textFieldDesc_InstruccionPrep.setText("prepa");
        CargaBasica.add(textFieldDesc_InstruccionPrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 930, 410, -1));

        textFieldDesc_ControlesEspeciales.setText("cuidado");
        CargaBasica.add(textFieldDesc_ControlesEspeciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 960, 410, 40));

        textFieldDesc_InfoAdicional.setText("infoad");
        CargaBasica.add(textFieldDesc_InfoAdicional, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1040, 410, -1));

        labelDesc_AQuienDirigido.setText("A quien va dirigido el producto:");
        CargaBasica.add(labelDesc_AQuienDirigido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1010, -1, 20));

        labelDesc_ControlesEspeciales1.setText("Controles y cuidados especiales");
        CargaBasica.add(labelDesc_ControlesEspeciales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 960, 230, 20));

        textFieldDesc_AQuienDirigido.setText("aquein");
        CargaBasica.add(textFieldDesc_AQuienDirigido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1010, 410, -1));

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(CargaBasica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(botonGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 73, Short.MAX_VALUE)
                .addComponent(CargaBasica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(botonGuardar)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldRNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldRNEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldRNEActionPerformed

    private void BuscarRNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarRNEActionPerformed
        try {
            Empresa empresa = this.recuperarDatosEmpresa(textFieldRNE.getText());
            if (empresa != null) {
                textFieldEmp_CUIL.setText(String.valueOf(empresa.getCUIT()));
                textFieldEmp_Nombre.setText(empresa.getNombre());
                textFieldEmp_RazonSocial.setText(empresa.getRazon_social());
                textFieldEmp_Email.setText(empresa.getEmail());
                textFieldEmp_Telefono.setText(String.valueOf(empresa.getTelefono()));
            } else {
                JOptionPane.showMessageDialog(null, "Numero RNE no encontrado.");
            }
        } catch (SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(panelCargaProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BuscarRNEActionPerformed

    private void textFieldEmp_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmp_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmp_EmailActionPerformed

    private void textFieldComp_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldComp_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldComp_NombreActionPerformed

    private void textFieldDesc_FormaUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDesc_FormaUsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDesc_FormaUsoActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        try {
            ProductoAlimenticio producto = new ProductoAlimenticio();
            Composicion composicion = new Composicion();
            Descripcion descripcion = new Descripcion();
            RNPA rnpa = new RNPA();
            
            producto.setNro_factura(Integer.valueOf(textFieldNroFactura.getText()));
            producto.setRotulo(textAreaRotulo.getText());
            
            composicion.setCAA(textFieldComp_CAA.getText());
            composicion.setContenido(textFieldComp_Contenido.getText());
            composicion.setDenominacion(textFieldComp_Denominacion.getText());
            //composicion.setFecha_duracion(textFieldComp_FechaDuracion.getText());
            composicion.setMarca(textFieldComp_Marca.getText());
            composicion.setNombre_comercial(textFieldComp_Nombre.getText());
            composicion.setNroytipo_registro_marca(textFieldComp_NroTipoMarca.getText());
            producto.setComposicion(composicion);
            
            descripcion.setControlesycuidados(textFieldDesc_ControlesEspeciales.getText());
            descripcion.setDestino_producto(textFieldDesc_AQuienDirigido.getText());
            descripcion.setForma_uso_producto(textFieldDesc_FormaUso.getText());
            descripcion.setInformacion_adicional(textFieldDesc_InfoAdicional.getText());
            descripcion.setIntrucciones_preparacion(textFieldDesc_InstruccionPrep.getText());
            descripcion.setLugar_venta(textFieldDesc_DondeVendido.getText());
            descripcion.setModo_conservacion(textFieldDesc_ModoConservacion.getText());
            descripcion.setPeriodo_aptitud(textFieldDesc_PeriodoAptitud.getText());
            producto.setDescripcion(descripcion);
            
            rnpa.setNumero(Integer.valueOf(textFieldRNPA.getText()));
            //rnpa.setFecha_vencimiento(fecha_vencimiento);
            producto.setRnpa(rnpa);
            //if estab_aCargar es null no tiene que dejar cargar
            producto.setEstablecimiento(estab_aCargar);
            
            boolean result = producto.guardar();
            if (result == true){
                JOptionPane.showMessageDialog(null, "correcto.");
            }else{
                JOptionPane.showMessageDialog(null, "error");
            }
            
        } catch (SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(panelCargaProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private Empresa recuperarDatosEmpresa(String nro_rne) throws SQLException, InstantiationException, IllegalAccessException {
        Empresa empresa_salida = null;
        try {
            estab_aCargar = Establecimiento.recuperarPorNroRNE(nro_rne);
            if (estab_aCargar != null) {
                empresa_salida = estab_aCargar.getM_Empresa();
            }

        } catch (SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Establecimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        return empresa_salida;
    }


    private Establecimiento estab_aCargar;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarRNE;
    private javax.swing.JPanel CargaBasica;
    private javax.swing.JSeparator SeparadorDatosEmpresa;
    private javax.swing.JSeparator SeparadorDatosProducto;
    private javax.swing.JSeparator SeparadorDatosProducto1;
    private javax.swing.JSeparator SeparadorDatosProducto3;
    private javax.swing.JSeparator SeparadorRegistroRNPA;
    private javax.swing.JSeparator SeparadorRegistroRNPA1;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCargaProdAlimenticio;
    private javax.swing.JLabel labelComp_CAA;
    private javax.swing.JLabel labelComp_Contenido;
    private javax.swing.JLabel labelComp_Denominacion;
    private javax.swing.JLabel labelComp_FechaDuracion;
    private javax.swing.JLabel labelComp_Marca;
    private javax.swing.JLabel labelComp_MateriasPrimas;
    private javax.swing.JLabel labelComp_Nombre;
    private javax.swing.JLabel labelComp_NroTipoMarca;
    private javax.swing.JLabel labelComposicion;
    private javax.swing.JLabel labelDatoEmpresa;
    private javax.swing.JLabel labelDatosDeLab;
    private javax.swing.JLabel labelDatosPA;
    private javax.swing.JLabel labelDesc_AQuienDirigido;
    private javax.swing.JLabel labelDesc_CaracteristicasEnvase;
    private javax.swing.JLabel labelDesc_ControlesEspeciales1;
    private javax.swing.JLabel labelDesc_ControlesEspeciales2;
    private javax.swing.JLabel labelDesc_DondeVendido;
    private javax.swing.JLabel labelDesc_FormaUso;
    private javax.swing.JLabel labelDesc_InfoAdicional;
    private javax.swing.JLabel labelDesc_InstruccionPrep;
    private javax.swing.JLabel labelDesc_ModoConservacion;
    private javax.swing.JLabel labelDesc_PeridoAptitud;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelEmp_CUIL;
    private javax.swing.JLabel labelEmp_Email;
    private javax.swing.JLabel labelEmp_NombreEmpresa;
    private javax.swing.JLabel labelEmp_RazonSocial;
    private javax.swing.JLabel labelEmp_Telefono;
    private javax.swing.JLabel labelFechaVencimiento;
    private javax.swing.JLabel labelNroActa;
    private javax.swing.JLabel labelNroFactura;
    private javax.swing.JLabel labelNumProtocolo;
    private javax.swing.JLabel labelNumRNE;
    private javax.swing.JLabel labelRNPA;
    private javax.swing.JLabel labelRegistroRNPA;
    private javax.swing.JLabel labelRotulo;
    private javax.swing.JTextArea textAreaRotulo;
    private javax.swing.JTextField textFieldComp_CAA;
    private javax.swing.JTextField textFieldComp_Contenido;
    private javax.swing.JTextField textFieldComp_Denominacion;
    private javax.swing.JTextField textFieldComp_FechaDuracion;
    private javax.swing.JTextField textFieldComp_Marca;
    private javax.swing.JTextField textFieldComp_Nombre;
    private javax.swing.JTextField textFieldComp_NroTipoMarca;
    private javax.swing.JTextField textFieldDesc_AQuienDirigido;
    private javax.swing.JTextField textFieldDesc_ControlesEspeciales;
    private javax.swing.JTextField textFieldDesc_DondeVendido;
    private javax.swing.JTextField textFieldDesc_FormaUso;
    private javax.swing.JTextField textFieldDesc_InfoAdicional;
    private javax.swing.JTextField textFieldDesc_InstruccionPrep;
    private javax.swing.JTextField textFieldDesc_ModoConservacion;
    private javax.swing.JTextField textFieldDesc_PeriodoAptitud;
    private javax.swing.JTextField textFieldEmp_CUIL;
    private javax.swing.JTextField textFieldEmp_Email;
    private javax.swing.JTextField textFieldEmp_Nombre;
    private javax.swing.JTextField textFieldEmp_RazonSocial;
    private javax.swing.JTextField textFieldEmp_Telefono;
    private javax.swing.JFormattedTextField textFieldFechaVencimiento;
    private javax.swing.JTextField textFieldNroActa;
    private javax.swing.JTextField textFieldNroFactura;
    private javax.swing.JTextField textFieldNroProtocolo;
    private javax.swing.JTextField textFieldRNE;
    private javax.swing.JTextField textFieldRNPA;
    // End of variables declaration//GEN-END:variables
}
