/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prueba;;
import Logica.*;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco
 */
public class Envase_prueba extends javax.swing.JFrame {

    /**
     * Creates new form Rubro
     */
    public Envase_prueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        capacidad_textfield = new javax.swing.JTextField();
        buttonInsertar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        material_tf = new javax.swing.JTextField();
        unidad_tf = new javax.swing.JTextField();
        material_selec = new javax.swing.JComboBox<>();
        unidad_selec = new javax.swing.JComboBox<>();
        cargar_unidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Envase");

        capacidad_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacidad_textfieldActionPerformed(evt);
            }
        });

        buttonInsertar.setText("Insertar");
        buttonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertarActionPerformed(evt);
            }
        });

        jLabel4.setText("unidad");

        jLabel5.setText("capacidad");

        jLabel6.setText("material");

        material_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                material_tfActionPerformed(evt);
            }
        });

        unidad_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidad_tfActionPerformed(evt);
            }
        });

        material_selec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "otro..." }));
        material_selec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                material_selecActionPerformed(evt);
            }
        });

        unidad_selec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "otro..." }));
        unidad_selec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidad_selecActionPerformed(evt);
            }
        });

        cargar_unidad.setBackground(new java.awt.Color(255, 51, 51));
        cargar_unidad.setForeground(new java.awt.Color(255, 255, 255));
        cargar_unidad.setText("cargar");
        cargar_unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar_unidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(material_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(capacidad_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(material_selec, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(unidad_selec, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                        .addComponent(buttonInsertar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(unidad_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(cargar_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cargar_unidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(capacidad_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(material_selec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unidad_selec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(material_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidad_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(184, 184, 184))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void capacidad_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacidad_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacidad_textfieldActionPerformed

    private void buttonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertarActionPerformed
        // TODO add your handling code here:
        /*Vector<String> mat_car= new Vector<String>();
        Vector<String> uni_car= new Vector<String>();*/
        
        Envase envase=new Envase();

        Boolean error=false, existe=false,existe1=false;
        envase.setCapacidad(this.capacidad_textfield.getText());
       
        if(material_tf.isEnabled() && unidad_tf.isEnabled()){
        envase.setMaterial(this.material_tf.getText());
        envase.setUnidad(this.unidad_tf.getText());
       }
       if(material_tf.isEnabled() && !unidad_tf.isEnabled()){ 
        envase.setMaterial(this.material_tf.getText());
        envase.setUnidad(this.unidad_selec.getSelectedItem().toString());
       }
       if(!material_tf.isEnabled() && unidad_tf.isEnabled()){    
        envase.setMaterial(this.material_selec.getSelectedItem().toString());
        envase.setUnidad(this.unidad_selec.getSelectedItem().toString());
       }

        try {
           //verificar existencia y guardar (en caso de no existir) materia y unidad.
            existe=envase.existe_material(envase.getMaterial());
            existe1=envase.existe_unidad(envase.getUnidad());
            if (existe)
            {JOptionPane.showMessageDialog(null, "Ya existe un material con ese nombre.");}
            else {    
            //guardarlo
            error=envase.guardar_material(envase.getMaterial());
            if(!error){JOptionPane.showMessageDialog(null, "material agregado correctamente.");}
            else {JOptionPane.showMessageDialog(null, "Hubo un error al agregar el material");}
            }
            if (existe1)
            {JOptionPane.showMessageDialog(null, "Ya existe una unidad con ese nombre.");}
            else {    
            //guardarlo
            error=envase.guardar_unidad(envase.getUnidad());
            if(!error){JOptionPane.showMessageDialog(null, "unidad agregado correctamente.");}
            else {JOptionPane.showMessageDialog(null, "Hubo un error al agregar la unidad");}
            }
           envase.guardar_envase(envase.getCapacidad(),envase.getMaterial(),envase.getUnidad()); 
        } catch (SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Envase_prueba.class.getName()).log(Level.SEVERE, null, ex);
        }
        //////////////////////////////////////////
        //////////////////////////////////////////
        
       //////////////////////////////////////////
       //////////////////////////////////////////
       
    }//GEN-LAST:event_buttonInsertarActionPerformed

    private void material_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_material_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_material_tfActionPerformed

    private void material_selecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_material_selecActionPerformed

        if (material_selec.getSelectedItem()=="otro..."){
            material_tf.setEnabled(true);
        }
        else{material_tf.setEnabled(false);}
    }//GEN-LAST:event_material_selecActionPerformed

    private void unidad_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidad_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidad_tfActionPerformed

    private void cargar_unidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar_unidadActionPerformed
                // TODO add your handling code here:
        Vector<String> mat_uni;
        Vector<String> mat_car;
        
        try{
            mat_uni=Envase.recuperarTodosUnidades();
            for(int i=0;i<mat_uni.size();i++){
            unidad_selec.addItem(mat_uni.elementAt(i));
            }
            mat_car=Envase.recuperarTodosMateriales();
            for(int j=0;j<mat_car.size();j++){
            material_selec.addItem(mat_car.elementAt(j));
            }
        }
        catch (SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Envase_prueba.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cargar_unidadActionPerformed

    private void unidad_selecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidad_selecActionPerformed
        
        if (unidad_selec.getSelectedItem()=="otro..."){
            unidad_tf.setEnabled(true);
        }
        else{unidad_tf.setEnabled(false);}
    }//GEN-LAST:event_unidad_selecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Envase_prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Envase_prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Envase_prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Envase_prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Envase_prueba().setVisible(true);
        });
    }
    
    
    
    DefaultListModel listaNombreModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInsertar;
    private javax.swing.JTextField capacidad_textfield;
    private javax.swing.JButton cargar_unidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> material_selec;
    private javax.swing.JTextField material_tf;
    private javax.swing.JComboBox<String> unidad_selec;
    private javax.swing.JTextField unidad_tf;
    // End of variables declaration//GEN-END:variables
}
